export type PhaseStatus =
  | 'completed'
  | 'active'
  | 'validation'
  | 'planned'
  | 'blocked';
export type RoadmapTrack = 'MVP' | 'R2' | 'R3' | 'R4' | 'R5';

export type RoadmapPhase = {
  code: string;
  track: RoadmapTrack;
  title: string;
  duration: string;
  status: PhaseStatus;
  outcome: string;
  gate: string;
  tasks: { label: string; done: boolean }[];
};

export const phases: RoadmapPhase[] = [
  {
    code: 'P0',
    track: 'MVP',
    title: '产品契约与工程地基',
    duration: 'W1',
    status: 'completed',
    outcome:
      '冻结 MVP 边界，并让 Rust 与 TypeScript 进入同一套可重复构建流程。',
    gate: '新机器执行一个入口命令即可完成格式检查、类型检查与空内核测试；ADR 明确 Game IR 是唯一权威源。',
    tasks: [
      { label: '定义 MVP 成功标准与明确非目标', done: true },
      { label: '确定 Rust + TypeScript + WGSL 技术边界', done: true },
      { label: '确定 Game IR、运行时状态与编辑器状态的权威关系', done: true },
      { label: '建立 MVP 进度控制面板', done: true },
      {
        label: '创建 Cargo workspace 与 TypeScript studio 工作区',
        done: true,
      },
      { label: '建立 format / lint / test / build 统一入口', done: true },
      { label: '记录首批架构决策 ADR', done: true },
    ],
  },
  {
    code: 'P1',
    track: 'MVP',
    title: 'AI 可编辑 Game IR',
    duration: 'W2–3',
    status: 'completed',
    outcome: '游戏世界首次成为可读、可校验、可迁移的结构化文件。',
    gate: '人或 AI 手写一个世界文件后，CLI 能给出精确到字段路径的校验结果，并生成一致的 Rust/TS 类型。',
    tasks: [
      { label: '设计稳定 ID、引用和命名空间规则', done: true },
      {
        label: '定义 project / world / entity / component Schema',
        done: true,
      },
      { label: '定义 command / event / snapshot Schema', done: true },
      { label: '从 Schema 生成 Rust structs 与 TypeScript types', done: true },
      { label: '实现带文件路径和字段路径的诊断输出', done: true },
      { label: '建立版本迁移机制与 golden fixtures', done: true },
    ],
  },
  {
    code: 'P2',
    track: 'MVP',
    title: '确定性无头内核',
    duration: 'W4–5',
    status: 'completed',
    outcome: '没有窗口和 GPU 也能加载世界、执行命令、推进 Tick 并重放结果。',
    gate: '同一世界、输入与 seed 连续运行 100 次产生相同快照哈希；失败可以定位到 Tick、系统和实体。',
    tasks: [
      { label: '实现 World、实体存储与组件注册表', done: true },
      { label: '实现固定时间步和明确的系统调度顺序', done: true },
      { label: '实现 Command → Event 执行管线', done: true },
      { label: '实现 seeded RNG 与时间抽象', done: true },
      { label: '实现快照、存档和输入日志', done: true },
      { label: '实现 replay 与状态哈希比较', done: true },
      { label: '实现结构化错误和系统级 tracing', done: true },
    ],
  },
  {
    code: 'P3',
    track: 'MVP',
    title: '最小 2D Runtime',
    duration: 'W6–7',
    status: 'completed',
    outcome: '把确定性世界投影成可交互的 2D 画面，但渲染不成为权威状态。',
    gate: 'Windows 上稳定运行示例世界；关闭渲染后，同一输入仍得到相同模拟结果。',
    tasks: [
      { label: '接入 winit 窗口与输入抽象', done: true },
      { label: '接入 wgpu 并完成基础渲染管线', done: true },
      { label: '实现正交相机、精灵批处理和层级排序', done: true },
      { label: '实现纹理、图集和资源句柄', done: true },
      { label: '实现输入映射与世界坐标拾取', done: true },
      { label: '提供碰撞区、ID 和性能调试叠层', done: true },
    ],
  },
  {
    code: 'P4',
    track: 'MVP',
    title: 'Codex 控制闭环',
    duration: 'W8–9',
    status: 'completed',
    outcome: 'Codex 不操作鼠标，而是通过结构化工具读取、修改、运行和验证游戏。',
    gate: '一句自然语言需求可生成 ChangeSet，经过预览和批准后落盘；失败时自动回滚且项目仍可构建。',
    tasks: [
      { label: '接入 Codex App Server 会话与流式事件', done: true },
      {
        label: '实现 schema.describe / project.query / world.query',
        done: true,
      },
      { label: '实现 change.plan / validate / apply / rollback', done: true },
      { label: '实现 simulation.run / snapshot / compare', done: true },
      { label: '实现 failure.explain 与机器可读诊断', done: true },
      { label: '加入工作区沙箱、权限分级和人工审批', done: true },
      { label: '建立 AI 操作轨迹与可重放审计记录', done: true },
    ],
  },
  {
    code: 'P5',
    track: 'MVP',
    title: '人类控制台 Studio',
    duration: 'W10–11',
    status: 'completed',
    outcome: '人类能看清 AI 正在做什么、为什么修改、测试是否通过，并随时干预。',
    gate: '开发者可在一个界面完成下达任务、审查 diff、批准修改、运行游戏、查看状态和回滚。',
    tasks: [
      { label: '实现任务对话与 Agent 活动流', done: true },
      { label: '实现项目 / 世界 / 实体检查器', done: true },
      { label: '实现 ChangeSet diff 与逐项审批', done: true },
      { label: '实现运行、暂停、单步和 seed 控制', done: true },
      { label: '实现快照时间线与状态对比', done: true },
      { label: '实现测试、日志与性能面板', done: true },
    ],
  },
  {
    code: 'P6',
    track: 'MVP',
    title: '类 SLG 垂直切片',
    duration: 'W12–13',
    status: 'completed',
    outcome: '用真实游戏验证内核，而不是继续堆抽象层。',
    gate: 'Codex 可以新增一个资源据点、修改产出规则、生成测试，并交付可完成一局的 Windows 构建。',
    tasks: [
      { label: '制作可探索地图与玩家移动单位', done: true },
      { label: '实现单位接触、合并和成长', done: true },
      { label: '实现粮仓、武器库、工厂与占领', done: true },
      { label: '实现自动生产、升级和资源循环', done: true },
      { label: '实现敌对单位、路径选择和基础策略', done: true },
      { label: '实现胜利条件、存档与一局完整流程', done: true },
      { label: '用批量无头模拟完成首轮平衡', done: true },
    ],
  },
  {
    code: 'P7',
    track: 'MVP',
    title: 'MVP 硬化与发布',
    duration: 'W14',
    status: 'completed',
    outcome: '形成可交给外部开发者试用、复现和反馈的第一版工具链。',
    gate: '全新环境按文档可在 30 分钟内完成安装、AI 修改、验证与构建；关键冒烟测试全部通过。',
    tasks: [
      { label: '建立端到端冒烟测试与崩溃恢复', done: true },
      { label: '记录性能基线和可接受预算', done: true },
      { label: '固定依赖版本并验证可复现构建', done: true },
      { label: '打包 Windows Runtime 与 Studio', done: true },
      { label: '完成快速开始、架构和工具协议文档', done: true },
      { label: '邀请首批开发者完成任务测试', done: true },
    ],
  },
  {
    code: 'P8',
    track: 'R2',
    title: 'Electron 外壳、项目系统与内置 Codex',
    duration: 'R2 · W1–3',
    status: 'completed',
    outcome: '安装一次 Studio，即可创建独立游戏项目并启动项目级 Codex 会话。',
    gate: '全新 Windows 环境无需 Node.js 或全局 Codex CLI：安装 Studio、登录、创建 Top-down Action 项目、通过 Project Doctor 并运行初始场景。',
    tasks: [
      {
        label: '建立 Electron main / preload / renderer 安全边界',
        done: true,
      },
      { label: '实现新建、打开、最近项目与单写入锁', done: true },
      { label: '实现项目格式与分层模板组合器', done: true },
      {
        label: '初始化 AGENTS.md、Skills、配置、场景、测试与 Git',
        done: true,
      },
      { label: '随 Studio 提供固定版本 Codex App Server sidecar', done: true },
      { label: '实现登录、流式事件、审批、进程健康与会话恢复', done: true },
      { label: '解析项目级 Engine MCP 配置且不写入机器绝对路径', done: true },
      { label: '实现可视化且机器可读的 Project Doctor', done: true },
      {
        label: '建立 Studio、项目、模板、协议与 sidecar 兼容策略',
        done: true,
      },
    ],
  },
  {
    code: 'P9',
    track: 'R2',
    title: '游戏开发 IDE 核心工作台',
    duration: 'R2 · W4–6',
    status: 'completed',
    outcome: '人类开发者可在 Studio 内完成常规 2D 游戏项目编辑与调试。',
    gate: '创建并编辑场景、预制体、输入、碰撞和测试；关闭重开 Studio 后，以完全一致的项目状态运行。',
    tasks: [
      { label: '实现项目文件树及安全的文件操作', done: true },
      { label: '实现使用稳定语义 ID 的场景层级', done: true },
      { label: '实现 2D 视口、网格、变换、吸附与 Tile 绘制', done: true },
      { label: '实现 Schema 驱动的组件 Inspector', done: true },
      { label: '实现脚本、Game IR、AGENTS 与 Skill 文本编辑', done: true },
      { label: '实现资源浏览、依赖、预览、导入与重新导入', done: true },
      { label: '实现运行、停止、暂停、单 Tick、seed 与 replay', done: true },
      { label: '实现日志、诊断、测试、性能与审计面板', done: true },
      { label: '实现统一事务 Undo / Redo 与崩溃恢复', done: true },
      { label: '实现调用统一命令注册表的 Command Palette', done: true },
    ],
  },
  {
    code: 'P10',
    track: 'R2',
    title: '项目级 Copilot 与 Engine MCP',
    duration: 'R2 · W7–9',
    status: 'completed',
    outcome:
      'Codex 能通过语义工具创建、运行、诊断、测试和构建游戏，人类保留最终控制。',
    gate: 'Codex 从新项目完成一次功能新增、运行调试、失败修复、测试生成和精确回滚；全过程不操作 Studio DOM 或鼠标。',
    tasks: [
      { label: '实现 ai-game-engine MCP Server', done: true },
      { label: '暴露项目、场景、实体、Prefab 与资源查询工具', done: true },
      { label: '暴露语义编辑工具并复用 Studio 命令注册表', done: true },
      { label: '暴露运行、调试、性能与实体观察工具', done: true },
      { label: '暴露测试、replay、批量模拟和构建工具', done: true },
      { label: '实现 Ask / Plan / Agent 三种 Copilot 模式', done: true },
      {
        label: '实现 Plan、Diff、Approve、Apply、Test、Rollback UI',
        done: true,
      },
      { label: '提供开发、测试、故障修复和美术方向项目 Skills', done: true },
      { label: '验证中断后的 Agent 与工具事务恢复', done: true },
    ],
  },
  {
    code: 'P11',
    track: 'R2',
    title: 'Tank Arena 单关垂直切片',
    duration: 'R2 · W10–12',
    status: 'completed',
    outcome:
      '用 Studio 和 Codex 制作第一关完整坦克玩法，并用真实开发暴露 IDE 能力缺口。',
    gate: '非引擎开发者只使用 Studio 即可理解、修改、游玩和测试第一关；IDE gap ledger 中阻塞项全部关闭。',
    tasks: [
      { label: '从 Top-down Action 2D 模板创建 Tank Arena', done: true },
      { label: '完成玩家移动、瞄准、射击、碰撞与伤害', done: true },
      { label: '完成可破坏墙体与基地防守失败条件', done: true },
      { label: '完成一种确定性敌人行为与波次生成', done: true },
      { label: '完成 HUD、分数、暂停、重开和最小存档', done: true },
      { label: '通过资源管线生成或导入原创占位美术与音效', done: true },
      { label: '录制确定性胜利与失败 replay', done: true },
      { label: '建立并清理 IDE_GAP_LEDGER 阻塞项', done: true },
    ],
  },
  {
    code: 'P12',
    track: 'R2',
    title: '完整五关与深度创作能力',
    duration: 'R2 · W13–16',
    status: 'completed',
    outcome: '证明 Studio 工作流可以支撑一款小而完整的原创游戏，而非单关演示。',
    gate: '五关全部通过 replay、冒烟和性能预算；人类编辑与 Codex 工具不会产生分叉的项目状态。',
    tasks: [
      { label: '完成四种地形及移动、碰撞和破坏规则', done: true },
      { label: '完成三种确定性敌人、感知与寻路', done: true },
      { label: '完成 Prefab、波次、关卡切换、计分与升级', done: true },
      { label: '完成动画、粒子、音乐、音效与必要无障碍设置', done: true },
      { label: '完成五个原创关卡及难度推进和存档恢复', done: true },
      { label: '建立视觉回归、replay、平衡批测和性能预算', done: true },
      { label: '验证生成资源审批、重试、导入和溯源流程', done: true },
      { label: '验证项目格式和模板升级迁移', done: true },
    ],
  },
  {
    code: 'P13',
    track: 'R2',
    title: '独立游戏构建与发布',
    duration: 'R2 · W17',
    status: 'completed',
    outcome:
      '从 Studio 一键导出只面向玩家的 Windows 游戏包，不携带开发工具链。',
    gate: '测试者只收到游戏包即可完成五关，无需安装 Studio、Codex、Node.js、Rust 或编译工具。',
    tasks: [
      { label: '实现 Build Settings 与开发/发布一键构建', done: true },
      { label: '只打包运行时所需逻辑和传递依赖资源', done: true },
      { label: '排除 Studio、Codex、源码、测试、缓存和密钥', done: true },
      { label: '生成哈希、许可证、资源溯源和版本清单', done: true },
      { label: '在干净机器验证启动、输入、存档、崩溃与通关', done: true },
      { label: '分离带诊断的 Development 与玩家 Release 构建', done: true },
      { label: '完成签名与安装包策略或明确分发限制', done: true },
    ],
  },
  {
    code: 'P14',
    track: 'R3',
    title: '产品纠偏与通用架构契约',
    duration: 'R3 · W1',
    status: 'completed',
    outcome:
      '把 P0–P13 重新定性为技术原型，冻结通用核心、能力模块、扩展和 Demo 的边界。',
    gate: '完成带文件证据的硬编码清单、脚本宿主确定性 Spike、架构 ADR、无指导用户基线记录和缺口台账。',
    tasks: [
      { label: '发布 Round 03 开发规格', done: true },
      { label: '发布 P14–P20 独立执行 Checklist', done: true },
      { label: '纠正人类面板的 Technical Prototype 基线', done: true },
      {
        label: '盘点 Studio、Schema、Runtime、MCP 中的 Tank/2D 假设',
        done: true,
      },
      { label: '按保留、能力化、Demo 化、替换、删除完成分类', done: true },
      { label: '冻结 core/capability/extension/demo 依赖规则', done: true },
      { label: '完成 TypeScript 沙箱宿主与确定性 Spike', done: true },
      { label: '冻结场景、脚本、事件、设置等项目文件 Schema', done: true },
      { label: '录制当前 Studio 无指导用户基线任务', done: true },
    ],
  },
  {
    code: 'P15',
    track: 'R3',
    title: '正式桌面 IDE Shell 与项目体验',
    duration: 'R3 · W2–3',
    status: 'validation',
    outcome:
      '交付无边框、可恢复、可停靠的桌面工作区，让首次使用者能理解每个区域。',
    gate: '干净安装后，无指导用户完成空项目创建、导航、设置、关闭和重开，并能解释所有可见区域。',
    tasks: [
      { label: '实现无边框窗口及自定义最小化、最大化和关闭', done: true },
      { label: '实现项目管理器与 Empty / Empty 2D / Empty 3D', done: true },
      { label: '实现 Activity Bar 与可切换左侧面板', done: true },
      { label: '实现树状 Project Files 与 Scene Outline', done: true },
      { label: '实现中央多文档标签与编辑器路由', done: true },
      { label: '实现 Inspector / Copilot 右侧切换面板', done: true },
      { label: '实现底部 Console / Problems / Tests / Profiler', done: true },
      { label: '实现全局、项目和安全凭据设置作用域', done: true },
      { label: '实现工作区恢复、首次引导和上下文帮助', done: true },
      {
        label: '实现项目打开/创建的即时反馈、真实阶段进度与防重复操作',
        done: true,
      },
      {
        label: '统一源代码管理工具栏、提交区、文件行、历史与 ChangeSet 视觉',
        done: true,
      },
      {
        label: '统一 Inspector 文件信息字号并纳入真实 Electron 计算样式门禁',
        done: true,
      },
      {
        label: '对齐中心与右栏分割线并阻止 Inspector/Copilot 内部分隔越界',
        done: true,
      },
      {
        label: '固化 Midnight Workshop 设计规范、Token、Agent Skill 与 CI 门禁',
        done: true,
      },
      {
        label: '通过键盘、焦点、高 DPI、无障碍与 renderer 崩溃恢复门禁',
        done: true,
      },
    ],
  },
  {
    code: 'P16',
    track: 'R3',
    title: '项目文件编辑器与语言服务',
    duration: 'R3 · W4–5',
    status: 'validation',
    outcome:
      '开发者不离开 Studio 即可编写、搜索、理解、诊断和审查项目代码与配置。',
    gate: '只用 Studio 创建并修复一个多文件 TypeScript 功能，所有错误都能跳转到正确文件、行和列。',
    tasks: [
      { label: '集成生产级多标签源码编辑器', done: true },
      { label: '支持 TypeScript、JSON、WGSL、Markdown 和文本', done: true },
      { label: '实现补全、类型、悬停、定义、引用和重命名', done: true },
      { label: '实现全项目搜索替换、格式化和符号导航', done: true },
      { label: '实现保存冲突、恢复、Git 状态与 Undo/Redo', done: true },
      { label: '实现诊断到文件、行、列的精确跳转', done: true },
      { label: '实现 Codex 行内和并排 Diff 审查', done: true },
      { label: '实现对象、脚本、System、Event 双向定位', done: true },
    ],
  },
  {
    code: 'P17',
    track: 'R3',
    title: '通用场景、对象、组件与 Prefab 创作',
    duration: 'R3 · W6–7',
    status: 'validation',
    outcome:
      '移除固定入口场景和 Tank/Tile 假设，建立可由能力模块扩展的通用创作模型。',
    gate: '项目创建并切换多个场景、组合 Prefab、添加自定义 Component、重开状态一致，生产代码没有游戏专用词汇。',
    tasks: [
      { label: '实现场景创建、切换、复制、删除和启动场景', done: true },
      { label: '实现对象层级、父子关系、多选、复制和删除', done: true },
      { label: '实现能力注册驱动的对象与 Component 创建', done: true },
      { label: '实现 Schema 驱动 Inspector 与自定义编辑器', done: true },
      { label: '实现 Transform2D、Transform3D 与 UI Transform', done: true },
      { label: '实现 Prefab 编辑、实例、覆盖、应用与还原', done: true },
      { label: '实现资源导入设置、重导入、依赖与修复', done: true },
      { label: '分离 Scene 创作视图和 Game 运行视图', done: true },
      { label: '把 Tank 专用能力迁移至独立 Example/Extension', done: true },
    ],
  },
  {
    code: 'P18',
    track: 'R3',
    title: '脚本生命周期、System、Event 与调试',
    duration: 'R3 · W8–9',
    status: 'validation',
    outcome:
      '项目 TypeScript 能定义每 Tick 行为、自定义规则和事件，并被确定性地调试与重放。',
    gate: '项目代码完成自定义固定 Tick 行为和 Event 生产/消费；失败 Replay 精确定位 Tick、System、对象、文件和行。',
    tasks: [
      { label: '实现版本化 TypeScript SDK 与沙箱宿主', done: true },
      { label: '实现对象完整生命周期钩子', done: true },
      { label: '强制 Fixed Update 与 Frame 表现边界', done: true },
      { label: '实现项目自定义 Component 与查询式 System', done: true },
      { label: '实现类型化 Command 与不可变 Event', done: true },
      { label: '实现显式调度阶段与稳定执行顺序', done: true },
      { label: '实现非重入事件队列和生产者/消费者索引', done: true },
      { label: '实现断点、暂停、单步、状态观察和调用栈', done: true },
      {
        label: '实现 Event Timeline、System Trace 和 Replay 调试',
        done: true,
      },
    ],
  },
  {
    code: 'P19',
    track: 'R3',
    title: '2D/3D 能力模块与全链路 AI 对等',
    duration: 'R3 · W10–11',
    status: 'validation',
    outcome:
      '通用核心按注册表加载最小 2D/3D 能力；Codex 能参与人类可以完成的每个交付环节。',
    gate: '人类和 Codex 独立完成同一组 2D/3D 创作任务，得到语义等价的项目文件、诊断、测试和构建结果。',
    tasks: [
      { label: '注册最小 2D Transform、Camera、渲染、拾取和碰撞', done: true },
      {
        label: '注册最小 3D Transform、Camera、Mesh、材质、灯光和碰撞',
        done: true,
      },
      {
        label: '统一 Schema、Inspector、Runtime、Renderer、MCP、Skill 注册',
        done: true,
      },
      { label: '完成 Copilot 登录、历史、流式对话、重试和中断', done: true },
      {
        label: '完成附件、模型、推理、Ask/Plan/Agent/Goal Composer',
        done: true,
      },
      { label: '完成 Goal、Plan、权限、预算、上下文和审批设置', done: true },
      { label: '完成 MCP、Skill、生成模型与凭据引用配置', done: true },
      { label: '从共享注册表暴露全部 AI 查询和语义命令', done: true },
      { label: '验证 Agent、工具事务和 ChangeSet 中断恢复', done: true },
    ],
  },
  {
    code: 'P20',
    track: 'R3',
    title: '独立用户验证与 Alpha 发布',
    duration: 'R3 · W12',
    status: 'validation',
    outcome:
      '通过互不相同的 2D、3D 和 Tank 回归项目证明通用性，并由真实用户完成无指导发布。',
    gate: '新开发者只使用已安装 Studio，从空项目完成 2D/3D 创作、脚本、事件、AI 修改、调试、测试和独立 Windows 导出。',
    tasks: [
      { label: '从 Empty 2D 制作并发布 2D Pong', done: true },
      { label: '从 Empty 3D 制作并发布 3D Collect Room', done: true },
      { label: '迁移并回归仅作为 Example 的 Tank Arena', done: true },
      { label: '执行干净安装的无指导用户任务', done: false },
      { label: '关闭全部阻塞可用性缺口并用新配置复测', done: false },
      { label: '执行确定性、性能、崩溃、迁移、安全和泄密门禁', done: true },
      { label: '验证三个不依赖开发工具的 Windows 玩家包', done: true },
      { label: '交付用户、脚本、MCP/Skill、扩展和迁移文档', done: true },
      { label: '打包并验证 AI Game Studio 0.2.0 Alpha', done: true },
    ],
  },
  {
    code: 'P21',
    track: 'R3',
    title: '真实 Tank 项目完成闭环',
    duration: 'R3 · Completion increment',
    status: 'completed',
    outcome:
      '补齐真实项目发现的通用引擎与 Copilot 缺口，并由同一个项目级 Codex Goal 完成游戏、测试和独立发布。',
    gate: 'Empty 2D Tank 项目通过可玩性、100 次确定性、结构化诊断和独立 Windows 包验证；全程保留 ChangeSet 审批与证据。',
    tasks: [
      { label: '实现运行时 Scene 切换和确定性对象生命周期', done: true },
      { label: '实现 Text2D/UI 独立玩家渲染和能力注册', done: true },
      { label: '把 collision.define_rule 暴露到 Engine MCP', done: true },
      { label: '常驻显示当前 Goal/Plan 与停止、移除控制', done: true },
      { label: '通过 P18/P19/P21 与完整发布门禁', done: true },
      { label: '恢复并完成真实 Tank 项目 Codex Goal', done: true },
      { label: '验证 100 次确定性与结构化失败诊断', done: true },
      { label: '验证独立 Windows Development/Release 包', done: true },
    ],
  },
  {
    code: 'P22',
    track: 'R4',
    title: '真实基线与可执行契约',
    duration: 'R4 · W1',
    status: 'completed',
    outcome:
      '把“接口存在”和“游戏能力完成”彻底分开，为全部占位建立协议、责任阶段和失败探针。',
    gate: '每个已知占位都有源码证据、严重级别、Owner、自动探针和真人复测要求；Studio 与 Player 的共享运行协议完成评审。',
    tasks: [
      { label: '发布 Round 04 真实游戏创作开发文档', done: true },
      { label: '建立 Round 04 独立执行 Checklist', done: true },
      { label: '建立分阶段人类观察任务与记录面板', done: true },
      { label: '按真实可玩结果重新校准人类进度面板', done: true },
      { label: '记录可复用实现与不完整占位边界', done: true },
      { label: '发布带源码行证据的完整占位清单', done: true },
      { label: '冻结持久 Runtime Session 与生命周期协议', done: true },
      { label: '冻结渲染、音频、输入、物理与调试消息协议', done: true },
      { label: '冻结稳定资源引用与运行时依赖解析', done: true },
      { label: '为全部 Empty 预设初始化共享输入 Action 清单', done: true },
      { label: '为 DOM 视口、合成碰撞和无效设置建立失败探针', done: true },
    ],
  },
  {
    code: 'P23',
    track: 'R4',
    title: '共享引擎视口与持续 Play Mode',
    duration: 'R4 · W2–3',
    status: 'completed',
    outcome:
      'Studio 与独立 Player 使用同一个运行世界和渲染数据，运行、暂停、单步不再是一次性快照。',
    gate: '同一输入下 Studio、无头 Replay 与 Player 状态一致；暂停和单步保留同一 Session；生产视口不再绘制 DOM 游戏对象。',
    tasks: [
      {
        label: '实现长生命周期 Runtime Session 和稳定 Session ID',
        done: true,
      },
      {
        label: '实现 Play / Pause / Step / Stop / Restart 状态机',
        done: true,
      },
      { label: '实现固定 Tick 输入路由与 RenderSnapshot 协议', done: true },
      { label: '让 Studio Game View 与 Player 复用同一投影路径', done: true },
      { label: '用引擎视口替换 Scene DOM/CSS 代理绘制', done: true },
      { label: '实现拾取、网格、相机和可拖动 Transform Gizmo', done: true },
      { label: '实现逐帧 Transform 预览与松手单事务持久化', done: true },
      { label: '实现权威 Tick 分配和低延迟 Runtime 输入通道', done: true },
      { label: '实现诚实的热重载、重启与状态迁移提示', done: true },
      { label: '完成预览崩溃隔离、恢复、MCP 和自动门禁', done: true },
    ],
  },
  {
    code: 'P24',
    track: 'R4',
    title: '完整最小 2D 游戏闭环',
    duration: 'R4 · W4–5',
    status: 'validation',
    outcome:
      '图片、输入、碰撞、声音和 UI 从项目文件贯通 Studio、脚本宿主、原生 Player 与发布包。',
    gate: '从 Empty 2D 完成的 Tank 机制在 Studio 和独立包中均可玩，并由物理世界产生碰撞、由真实资源产生图像和声音。',
    tasks: [
      {
        label: '完成 Camera2D、Sprite2D、纹理、图集与资源生命周期',
        done: true,
      },
      { label: '完成项目输入 Action 与键鼠映射', done: true },
      { label: '集成 Collider2D / RigidBody2D 和确定性碰撞事件', done: true },
      { label: '完成 WAV/OGG 播放、音量、循环、总线和静音', done: true },
      { label: '完成菜单、HUD、得分、暂停、胜负所需 UI', done: true },
      { label: '实现可达性资源打包和精确缺失引用诊断', done: true },
      { label: '补齐全部 2D 能力的人类 UI、MCP、Skill 与回滚', done: true },
      { label: '从 Empty 2D 独立完成人类与 Codex 等价任务', done: false },
    ],
  },
  {
    code: 'P25',
    track: 'R4',
    title: '诚实的最小 3D 游戏闭环',
    duration: 'R4 · W6–7',
    status: 'validation',
    outcome:
      '用真正的透视、深度、网格、材质、灯光和 3D 碰撞替代等距基础几何证明。',
    gate: 'Collect Room 从 Empty 3D 构建，在 Studio 与 Player 中证明透视遮挡、灯光、碰撞、输入、得分和独立发布。',
    tasks: [
      { label: '实现透视 Camera3D 与深度测试', done: true },
      { label: '实现层级 Transform3D 和移动/旋转/缩放 Gizmo', done: true },
      { label: '实现基础与导入静态 Mesh 资源', done: true },
      { label: '实现材质颜色/纹理与方向光', done: true },
      { label: '实现 3D 拾取、视口导航、Collider 和 RigidBody', done: true },
      { label: '补齐 3D 能力的人类 UI、MCP、Skill 与机器测试', done: true },
      { label: '从 Empty 3D 构建并打包 Collect Room', done: true },
    ],
  },
  {
    code: 'P26',
    track: 'R4',
    title: '日常 IDE、设置与资源供应商闭环',
    duration: 'R4 · W8–9',
    status: 'validation',
    outcome:
      '移除可见但无效的控件，让编码、测试、调试、版本管理、设置和资源生成可以日常使用。',
    gate: '开发者不离开 Studio 完成编码、调试、测试、资源生成、Diff、提交、关闭重开；每个设置有效、明确禁用或不存在。',
    tasks: [
      { label: '完成 File/Edit/View/Project/Run 菜单', done: true },
      { label: '完成测试发现、逐项结果、输出、重跑和源码定位', done: true },
      { label: '完成源码断点、调用栈、Scope、Watch 和逐步调试', done: true },
      { label: '完成终端/任务输出、文件监听和外部冲突处理', done: true },
      {
        label: '完成文件 Inspector、Prefab、材质和最小动画编辑器',
        done: true,
      },
      {
        label: '统一生成、测试及工具面板的紧凑字号与暗色控件外观',
        done: true,
      },
      { label: '完成 Git 提交、历史、分支、冲突、Stash 和远端', done: true },
      { label: '完成 Capability/Extension 管理和健康检查', done: true },
      {
        label: '使 Studio、Agent、MCP、Skill 和 Provider 设置真实生效',
        done: true,
      },
      {
        label: '接入 OpenAI/百炼生成供应商并完成路由、成本、审批和溯源',
        done: true,
      },
      {
        label: '让 Agent 按图片/语音生成能力自动解析项目 Provider 与模型',
        done: true,
      },
      {
        label: '统一命名凭证管理，并按供应商动态生成连接表单',
        done: true,
      },
      {
        label: '按供应商、命名凭证和动态模型目录配置五类生成工具',
        done: true,
      },
      {
        label: '提供每次、预算内和预授权三种生成审批策略',
        done: true,
      },
      {
        label: '通过 Electron 主进程安全桥隔离 MCP 与供应商密钥',
        done: true,
      },
      { label: '删除或明确禁用全部可见无效控件', done: true },
    ],
  },
  {
    code: 'P27',
    track: 'R4',
    title: '独立游戏完成与 Preview 发布',
    duration: 'R4 · W10',
    status: 'validation',
    outcome:
      '由未参与实现的新开发者证明 Studio、Codex 和 Player 已形成真实游戏制作与发布闭环。',
    gate: '新参与者无指导完成 2D/3D 修改、调试、AI 审阅、测试和独立构建；无阻塞缺口，全部证据与哈希入库。',
    tasks: [
      { label: '从干净 Empty 2D 完成 Tank Arena', done: false },
      { label: '从干净 Empty 3D 完成 Collect Room', done: false },
      { label: '在两个项目中完成 Codex 功能、测试、诊断和修复', done: false },
      { label: '通过确定性、Replay、迁移、性能和崩溃恢复门禁', done: true },
      { label: '通过凭据泄漏、资源可达性与包内容门禁', done: true },
      { label: '在干净 PC 运行 Development 与 Release 包', done: false },
      { label: '执行完整无指导人类观察任务', done: false },
      { label: '修复全部 Blocker 并用新配置复测', done: false },
      { label: '发布限制、证据索引、Preview 包与 SHA-256', done: true },
      { label: '生成角色隔离验收包、结构化结果与哈希验证器', done: true },
    ],
  },
  {
    code: 'P28',
    track: 'R5',
    title: '完成闭环契约与真实基线',
    duration: 'R5 · W1',
    status: 'completed',
    outcome:
      '把“Copilot 有工具”和“Copilot 能完成游戏”彻底分开，冻结从高层目标到独立游戏包的权威、状态、审批和证据边界。',
    gate: 'Round 05 每项结果都有稳定协议、Owner、机器探针和真人旅程；面板不从 Round 04 工具或 Mock 成功推断游戏完成。',
    tasks: [
      { label: '发布 Round 05 Copilot 游戏完成开发规格', done: true },
      { label: '建立 Round 05 独立执行 Checklist', done: true },
      { label: '建立 Round 05 人类观察面板与记录协议', done: true },
      { label: '定义方块 Tank 到独立游戏包的标准旅程', done: true },
      { label: '区分产品决策、必要审批、澄清、指导与手工作弊', done: true },
      { label: '记录生成、导入、视觉观察与 Goal 恢复的真实边界', done: true },
      { label: '建立并通过 P28 Round 05 合同门禁', done: true },
      { label: '冻结 Completion Run 与稳定状态/身份协议', done: true },
      { label: '冻结媒体任务、候选审核与事务导入协议', done: true },
      { label: '冻结可寻址运行画面与音频观察协议', done: true },
      { label: '为全部起始缺口分配 Owner、探针与证据', done: true },
    ],
  },
  {
    code: 'P29',
    track: 'R5',
    title: 'Agent 原生媒体任务与审核导入',
    duration: 'R5 · W2–3',
    status: 'active',
    outcome:
      'Codex 按能力而非供应商细节生成图片和游戏声音，比较候选，并把人类选择作为可回滚 ChangeSet 导入项目。',
    gate: '图片与音效真实调用、进度、审批、候选、拒绝、重试、取消、导入和回滚均可由 Copilot 驱动，且不泄密、不重复计费。',
    tasks: [
      {
        label: '拆分 image、soundEffect、music 与 speechGeneration 能力',
        done: true,
      },
      { label: '保留并验证旧 audio 路由迁移', done: true },
      { label: '实现生产图片与游戏音效适配器', done: true },
      { label: '实现稳定 Job ID、幂等键、进度与失败分类', done: true },
      { label: '把三种审批策略应用到初次调用与重试', done: true },
      { label: '让 Copilot 可查看、播放、比较和推荐候选', done: true },
      { label: '实现候选拒绝、再生成、取消和祖先记录', done: true },
      { label: '通过 ChangeSet 事务导入文件、清单、溯源与引用', done: true },
      { label: '实现事务回滚与中断恢复', done: true },
      { label: '通过成本、幂等与跨边界凭据脱敏机器门禁', done: true },
      { label: '完成真人候选审核、付费等待与导入理解门禁', done: false },
    ],
  },
  {
    code: 'P30',
    track: 'R5',
    title: '视觉运行观察与自动修复循环',
    duration: 'R5 · W4–5',
    status: 'active',
    outcome:
      'Codex 能看到可寻址的真实运行帧、资源解析、UI 边界和音频事件，并用这些证据发现和修复呈现问题。',
    gate: 'Codex 只用结构化工具发现并修复纹理、层级/轴心、UI、音频和打包资源故障，Studio 与 Player 证据一致。',
    tasks: [
      { label: '实现 runtime.capture_frame 与可检查图像产物', done: true },
      {
        label: '暴露 Drawable、资源、图层、Atlas、Pivot 与回退状态',
        done: true,
      },
      { label: '暴露 UI 边界、溢出、可见性和交互目标', done: true },
      { label: '暴露音频事件、Clip、Bus、音量和播放诊断', done: true },
      { label: '建立菜单、游戏、暂停、胜负的确定性检查点', done: true },
      { label: '实现 Studio 与 Player 检查点对比', done: true },
      {
        label: '让诊断定位稳定 Scene/Object/Component/Asset/Tick',
        done: true,
      },
      {
        label: '通过观察读取、迁移拒绝、篡改检测、种子故障修复和回滚门禁',
        done: true,
      },
      { label: '通过独立真人的诊断证据与修复建议理解门禁', done: false },
    ],
  },
  {
    code: 'P31',
    track: 'R5',
    title: 'Copilot 完成 Tank 正式游戏',
    duration: 'R5 · W6–7',
    status: 'active',
    outcome:
      '同一个项目 Goal 把逻辑可玩的方块 Tank 升级成画面、声音、菜单、反馈、测试和独立包完整的小型游戏。',
    gate: '正式资源替换所需占位，玩法语义和确定性保持，菜单到胜负完整可玩，Studio/Player 与 Development/Release 包全部通过。',
    tasks: [
      { label: '创建版本化 Tank 美术风格 Skill', done: true },
      { label: '建立占位清单、素材 Brief 与覆盖矩阵', done: true },
      { label: '验证 9 个视觉候选的格式、哈希、身份与待审核边界', done: true },
      {
        label: '在真实 Electron 资源面板显示 9 个可审核候选且查看不导入',
        done: true,
      },
      {
        label: '按状态筛选生成任务并默认聚焦 9 个待审核候选',
        done: true,
      },
      { label: '生成并审核玩家、敌人、子弹、墙、地面和特效资源', done: true },
      { label: '生成并审核射击、命中、爆炸、UI 与比赛声音', done: true },
      {
        label: '由内置 Copilot 用 ElevenLabs 真实生成音乐及射击源候选',
        done: true,
      },
      { label: '交付短音效 WAV 加工工具并由原 Copilot 产出母版', done: true },
      { label: '完成首批音乐与射击母版试听及正式导入', done: true },
      { label: '修复并验证实际安装版候选音频播放器', done: true },
      {
        label: '由原 Copilot 接线音乐与射击并验证场景播放生命周期',
        done: true,
      },
      {
        label: '导入用户认可的受击母版并由 Copilot 接线、完成回归',
        done: true,
      },
      {
        label: '把 Shape/UI 占位替换成资源化 Component 与 Prefab',
        done: true,
      },
      { label: '完成菜单、帮助、HUD、暂停、胜负和重开呈现', done: true },
      { label: '保留碰撞、战斗、得分、场景和稳定语义 ID', done: true },
      { label: '运行资源、玩法、Replay、视觉和音频检查点', done: true },
      { label: '提供可执行状态断言并验证错误期望必然失败', done: true },
      {
        label: '交付字形/面板安全区断言并通过实际安装版正反例验证',
        done: true,
      },
      {
        label: '由内置 Copilot 为 Tank 编写安全区断言并完成双分辨率实帧验收',
        done: true,
      },
      {
        label: '让暂停、UI、音量与胜负测试执行真实断言，而非只列说明',
        done: true,
      },
      { label: '构建并运行独立 Development 与 Release 包', done: true },
      { label: '完成真人完整可玩与审美验收', done: false },
    ],
  },
  {
    code: 'P32',
    track: 'R5',
    title: 'Goal 恢复、预算与质量门禁',
    duration: 'R5 · W8',
    status: 'completed',
    outcome:
      '长 Goal 在生成、审批、审核、ChangeSet、运行和构建的任意等待点都能诚实恢复，且副作用只执行一次。',
    gate: '全部命名中断点可恢复或安全终止；停止不删除证据，重启不重复计费，凭据和私有响应不进入项目或包。',
    tasks: [
      {
        label: '持久关联 Goal、Plan、Tool、Job、ChangeSet、Test 与 Build',
        done: true,
      },
      { label: '恢复 Provider 执行与付费审批等待', done: true },
      { label: '恢复候选审核与 ChangeSet 等待', done: true },
      { label: '修复 Plan 误报、消息串接、自动续轮与重复恢复点', done: true },
      {
        label: '隔离项目 Goal 的付费授权，并让 MCP 应用已批准的变更',
        done: true,
      },
      { label: '恢复 Runtime、测试和构建故障', done: true },
      {
        label: '提供可读取的拒绝原因、审核历史和即时提案刷新（候选包已验证）',
        done: true,
      },
      { label: '实现有界重试、退避和重复副作用拒绝', done: true },
      { label: '保持预算在取消、拒绝、重试与重启间一致', done: true },
      { label: '实现 Goal 停止、保留证据与安全移除', done: true },
      { label: '验证并发人类修改不被恢复与回滚覆盖', done: true },
      { label: '通过干净配置的安全、崩溃、迁移和性能门禁', done: true },
    ],
  },
  {
    code: 'P33',
    track: 'R5',
    title: '独立 Copilot 验收（负责人决定延期）',
    duration: 'R5 · W9',
    status: 'planned',
    outcome:
      '由未参与实现的用户只在已安装 Studio 中监督 Codex，把给定方块 Tank 完成、验证并打成独立游戏包。',
    gate: '2026-09-06 产品负责人确认 R5 验收结项，独立 A–E 旅程延期、NOT_RUN，不再阻塞本轮；原无指导验收标准保留供后续执行。',
    tasks: [
      {
        label: '固定不改动原工作区的源码快照，并校验候选包与源码绑定',
        done: true,
      },
      { label: '构建并固定 Studio 与输入项目候选', done: true },
      { label: '确定独立验收的参与者与测试预算', done: false },
      {
        label: '汇总本地 Studio、完整游戏项目、双包、源码快照和证据',
        done: true,
      },
      { label: '生成参与者/观察员角色隔离验收包', done: true },
      { label: '执行 Goal/Plan 与工具状态理解旅程', done: false },
      { label: '执行媒体生成、候选审核、导入与回滚旅程', done: false },
      { label: '执行 Tank 完成、视觉诊断和修复旅程', done: false },
      { label: '执行中断、恢复、取消与预算完整性旅程', done: false },
      { label: '执行独立包、干净机器与重开继续旅程', done: false },
      { label: '修复全部 Blocker 并以新配置复测', done: false },
      { label: '发布证据、限制、项目、游戏包与 SHA-256', done: false },
    ],
  },
];

export const roadmapMeta = {
  ownerAccepted: true,
  acceptanceSummary: 'R5 已验收结项 · P33 独立验收延期（未执行）',
  currentRound: 'ROUND 05',
  baselineRelease: 'Round 04 · 0.3.0 Preview machine candidate',
  estimate: '2026-09-06 · 负责人验收通过',
  objective:
    'R5 已验收结项：Copilot 工具链、正式素材、完整 Tank 与独立游戏包已交付；P33 独立验收延期，未冒充通过。',
  firstGame: 'Copilot-completed Tank · placeholder to package',
  baselineTrack: 'R4' as RoadmapTrack,
  activeTrack: 'R5' as RoadmapTrack,
  lastReview: '2026-09-06',
} as const;

export const roundDeliverables = [
  {
    label: 'Agent 原生制作',
    value: 'Goal → Tool Graph',
    detail: '一个高层目标驱动生成、导入、创作、运行、测试、修复与构建',
  },
  {
    label: '媒体生产',
    value: 'Reviewed Assets',
    detail: '真实图片/音效、成本审批、候选比较、ChangeSet 导入、溯源与回滚',
  },
  {
    label: 'AI 可观察',
    value: 'Frame + Runtime Evidence',
    detail: 'Codex 可检查运行帧、资源、UI、音频、诊断与 Studio/Player 差异',
  },
  {
    label: '完整游戏',
    value: 'Real Tank',
    detail: '正式美术、声音、菜单、HUD、反馈、胜负、重开与确定性玩法',
  },
  {
    label: '可靠长任务',
    value: 'Resume Exactly Once',
    detail: '生成/审批/审核/ChangeSet/构建可恢复，预算稳定且不重复计费或写入',
  },
  {
    label: '验收决定',
    value: '负责人验收通过',
    detail: 'R5 已结项；P33 独立验收延期，未执行项与原始证据如实保留',
  },
] as const;

export const baselineFindings = [
  '2026-09-06：产品负责人明确确认当前 R5 交付验收通过、可以结项，并将 P33 独立验收延期。A–E 仍为 NOT_RUN，原任务勾选与历史证据保留。结项记录：docs/rounds/ROUND-05-ACCEPTANCE.json。',
  '本次验收交付为 Studio 0520a5c0… 与 Tank 修订 27bc3a91… / Release ffffa361…：执行反馈、旋转单位修复、22 项游戏测试、全量 check 及双包验证通过。三文件游戏修正由监督侧通过 ChangeSet 完成，不冒充内置 Copilot 独立验收。以下为历史推进记录。',
  '本地交付已汇总到 r5-delivery-0.4.0-preview.1-6Pcp3b：Studio、Tank 源码、Development/Release、角色隔离验收资料、源码 bundle、独立测试输入与机器日志齐备。没有替换原安装，也没有新素材费用；下一步需要真实独立验收者，不再重复制作或逐份音频审批。',
  '0.4.0 候选已完成：2ede62d7… 来自干净源码 f41d6c02…，完整 check、R5 专项门禁、289 文件便携包及安装生命周期通过；正式角色隔离验收套件已具备候选资格。原安装与未提交改动均保留，A–E 真人旅程仍未开始。',
  '一次 P31 测试输入缺失已解决：9 张早期候选 PNG 不属于 Git 源码，现已归档为带哈希的独立测试输入 eefcb0a8…。保留失败日志，在隔离目录补齐后原测试通过；没有改测试、生成新素材、复制凭据或动最终游戏。',
  '完整 Tank 项目已归档：163 个源文件、19 份资源，项目 ZIP 0868333e…；Development 112c2b31…、Release 95aac9da… 同目录交付。隔离项目验证、素材哈希、溯源/限制元数据与文本凭据扫描通过，原项目未改。元数据不等于商业授权证明，独立真人和断网验收仍未完成。',
  '最后短流程已闭合：菜单→帮助→设置（80→70→80、静音→取消）→暂停→恢复→返回菜单，123 Tick、六状态／十二组对照全部通过；退出时音乐停止，32 条音频事件一致。最终 Development 112c2b31… 与 Release 95aac9da… 已按 ZIP、回执与内容逐项核验。测试素材不再需要逐份批准；独立真人与网络隔离验收仍保持未完成。',
  '可玩 Release 95aac9da… 已产出。两个实际 ZIP 独立解压后通过 68/26 个内容哈希、19 份素材、原生 GPU 启动及胜利／静音战败／重开三条长实录；两个分辨率的帧、状态、完整音频与原 Player 一致。菜单／设置／暂停短流程也已完成，P33 真人旅程尚未进行。旧 d58c1003… 审批已核实被合并提案替代并关闭，游戏文件未改。',
  '最终版整局胜利已复核：原 Copilot 从正常菜单通过移动与射击完成 1008 Tick，得分 600、剩余生命 2/5。1280×720 与 960×540 的 Studio/Player 状态、帧和全部 106 条音频事件一致，胜利音恰好一次，无缺失资源或播放失败。失败／重开／设置实录和最终双包也已完成，P33 真人验收未冒充完成。',
  'Studio 卡死修复包 37fc0b2e… 已通过全量 check 和安装生命周期门禁，并实际替换安装；287 个内容哈希、实际安装版 UI 与四组运行时一致性复核通过，旧包 d632ef94… 可恢复。修复消除了写文件时的短暂缺失与后台异常模态框。原游戏和凭证未被安装流程修改。',
  '原 Copilot 已完成全部音频接线，修订 d7ea102d…。22 项实际测试／276 断言与隔离审核完全一致；三组 600 Tick 单次播放检查、确定性回放和回滚通过。19 份素材（9 图片、10 音频）的来源链有效，音频逐份确认已结束。最终实录与双包验证已通过，独立真人验收仍开放。',
  '重试已恢复原 Studio Copilot：100ms 导航音和 680ms 墙体破坏音均已导入、补全溯源并接线。导航通过 11 组确定性探针；墙体修正版 f1a02d7e… 通过 20 测试／255 断言、销毁／非致命／空闲探针和精确回滚，已由原 Copilot 应用。原项目修订 77be28e9… 及实际测试的代码／状态／音频与审核一致。Copilot 已完成读取拒绝原因、自行修正、提交并应用的闭环；监督没有代写或直接应用游戏文件。其余 UI／比赛声音、最终日志／双包与独立真人验收仍开放。',
  '审核反馈版 dbf2197c… 已安装，旧安装可恢复。287 个内容哈希、20 测试／255 断言的新旧运行时一致性，以及实际安装版 150% DPI、拒绝原因／历史／冲突和崩溃恢复门禁均通过。原项目已重开，原 Copilot 已读取反馈并完成墙体修复；审核界面交付已完成，独立真人验收仍开放。外层 Goal 当前为 active。',
  '用户认可的 100ms UI 确认音已由原 Copilot 导入、补强溯源并接线，项目修订 cdffc27d…。20 测试／255 断言、14 组确定性探针与精确回滚通过；实际音频会话报告也匹配审核，Tick 8／16 各触发一次。110ms 返回音后来获得认可并导入；监督未代写或应用游戏源文件。',
  '早期素材审计：原 Copilot 已补齐 3 份旧音频的 Skill／Brief 关联，修订 b6e76869…。当时 15 份已导入素材的文件、候选审阅、来源与导入链全部通过核验，精确应用与回滚通过。仅补充后期项目关联，不冒充供应商原始输入；后来导入的第 16 份返回音单独验收，不沿用旧审计。',
  '资源面板卡顿已复现并修复：同一音频的重复预览由 5 次降为 1 次，采用哈希缓存、单请求队列与完成后轮询。WAV／MP3／9 张图片、P15 界面门禁和 npm run check 全部通过。新包 87cb8897… 已实际安装，287 个哈希、150% DPI 界面和四组新旧运行时一致性检查通过；旧版可恢复。',
  'R5 继续推进，尚未完成：音乐、射击和用户认可的 180ms 受击 WAV 已由原 Copilot 导入并接线，19 测试／252 断言及隔离审查通过。真实重开暴露的停止音频通道错误已修复，并由当前修订实录验证。其余破坏／UI／比赛音效、音频完备的最终包和独立真人验收仍开放；旧阶段获胜日志不能替代最终版本验收。监督没有代写或直接应用游戏文件。',
  '音频通道／供应商合并修复 ae576cfe… 已安装，287 个文件哈希一致且旧安装可恢复。20eff586… 的 84 Tick 静音／重开／返回、2233 Tick 战败／静音重开及 6202 Tick 获胜实录，均通过两种分辨率的 Studio／Player 核验：无音频缺失、播放失败或诊断，完整音频事件与画面一致。获胜为 600 分、敌人归零、HP 2/5。此前隔离候选 4a670004… 全量及干净安装／升级／恢复回归也通过；未重复安装。安全错误分类与 450 字符预检已交付，历史失败任务未重试。',
  '音频播放与 Scene 销毁修复 e3558835… 已通过完整 npm run check、安装／升级／恢复并安装，287 个内容哈希一致且旧安装可恢复。实际安装版候选 WAV/MP3 均加载并推进播放时钟，外部媒体仍被阻断；修改只允许本地 data 媒体，保留 UI 风格和候选不自动导入边界。',
  '内置 Copilot 已应用 UI 安全区和 5820aaf8… 行距修复；实际项目 17ae462e… 的 19 项测试／246 条断言全部通过，包括 76 条双分辨率 fitsUiContent。正常入口胜利、失败、静音重开日志全部通过 Studio/Player 双分辨率状态和 PNG 核验；Development 0f140cfc… / Release 4ae391a8… ZIP 经独立解压、三条路线回放和原生 GPU 启动验证通过。这是尚未加入正式音效的阶段包，不是完整游戏交付。',
  '共享测试历史与包验证增量已交付：实际 Tank 测试面板显示 19 项“上次通过”，夹具不再列为测试。build.verify_package / build.read_verification 及构建面板入口已安装；安装包自身的 MCP 在隔离示例中完成双配置构建、可信 Player 启动和原生截图。最终音频完备的 Tank 包仍待重建验收。',
  'ElevenLabs 首批正式音频闭环已到导入：生成 → MCP 加工/检查 → 用户试听认可 → 候选选择 → 监督核验批准 → 原 Copilot 应用。两份母版均为 48kHz PCM16 WAV，源件、哈希与加工链保留，供应商调用仍各一次、费用未知。此结果不等于后续音效、无缝循环、整游戏听感或 P33 已验收。',
  '此前音频链路修复 aa63a769… 通过完整 check、安装/升级/恢复及 287 内容哈希检查：Player 新增 MP3 解码，候选信息改为实际解码测量，坏音频与损坏历史任务有明确失败状态。该批隔离测试音频不是正式 Tank 音效；正式 ElevenLabs 生成与新母版进展见上方。',
  '真实窗口引擎修复已包含在当前安装：GPU 深度附件、贴图朝向、原生快捷键及跨 Tick 生命周期修复通过完整 check／P30。此前 UI 提案虽通过 18 项／164 条断言，双分辨率实帧仍压框而被拒绝。当前已进入真实内容区断言修复，保留量测 inset 与 6 px 余量；旧日志／旧游戏包不能冒充新版本验收。',
  '用户已授权外层监督者推进 R5、处理审核和必要付费。内置 Copilot 已接线九张正式图片，菜单和 HUD 已迁移到 UI 组件，保留玩法 ID 与碰撞。UI 与终局输入修复后，实际项目 17 项测试、107 条断言全部通过；真实胜负/静音重开及两个独立游戏包回放通过。正式音效、音频完备的最终包和独立真人验收仍开放。',
  '用户 Tank 与仓库 Neon Bastion 示例是两个项目：示例的 9 个候选不等于用户项目已有资源。用户项目九张图片已完成溯源导入、哈希核验与接线；PNG 透明通道检查纠正了底色误判，未因此重复付费生成。接线不等于最终视觉通过，正式音效路由和完整发行验收仍缺失，图片未知费用不等于免费。',
  '新增限时、精确项目和线程匹配的付费授权，仅对当前活动 Goal 的 Completion Run 任务生效，历史测试和其他项目保留原审批策略；MCP 可应用已批准的 ChangeSet，但不能自行批准或重复应用。内部授权推进不计入独立真人验收。',
  '19410ce9… 安装包已通过全量/P30、安装恢复和 287 个内容文件哈希核验。新版真实 977 Tick 战败/静音重开与 1175 Tick 胜利日志，在两种分辨率的 Studio/Player 状态和画面均一致；胜利最后 175 个连续快照也一致。Copilot 产出的 Development 3b80cfed… / Release 13011e00… ZIP 均经独立解压、内容核验和同日志回放通过；没有把总线事件当成正式声音。',
  '正式音频来源、受控加工和安装版候选试听已打通，不再缺少 ElevenLabs 凭据；剩余是其余音效制作／试听／导入、事件接线，以及新修订的完整游戏回归与打包。用户对音乐、射击和受击 WAV 的认可均单独记录，不替代整游戏听感、无缝循环或独立真人 Journey A–E。',
  '长会话修复已通过全量及安装门禁：过滤 Windows Git 根目录反馈循环、原子替换变更记录、保留长对话中的 Goal 控件，并修复测试失败却标为通过的问题。MCP 默认返回状态摘要，完整差异和测试证据可按 ID 读取；当前 39 项提案回复体积减少 97%。原项目已恢复，持续运行体验仍在观察，不等于 R5 完成。',
  'Round 05 已完成开发规格、独立 Checklist、人类观察面板和可执行 P28 合同检查；当前仅代表计划与基线成立，不代表 Copilot 已完成游戏。',
  '标准输入是逻辑可玩但 asset-manifest 为空、仍使用 Shape2D 占位的 Tank 项目；标准输出是具备正式资源、声音、菜单/HUD/反馈、测试、Replay 和独立 Windows 包的小型完整游戏。',
  '项目 Codex 已能通过 Engine MCP 查询和修改 Scene、Prefab、Component、脚本、输入与碰撞，并能运行、调试、测试、Replay、构建和发布；Round 05 要证明这些工具由一个长期 Goal 正确编排。',
  'P29 机器门禁已贯通 OpenAI/百炼图片、百炼 TTS、ElevenLabs 音效/音乐，以及 image、soundEffect、music、speechGeneration 的能力级路由、参数校验、费用/审批和结构化诊断；真人 Journey B 仍开放。',
  '候选选择不再是 Codex 可调用的直接写入命令：Codex 只能带证据推荐，人类选择后由一个可预览 ChangeSet 事务写入文件、Asset 清单、溯源、导入设置和所拥有的 Scene 引用，并可精确回滚。',
  'P30 机器门禁已提供真实 PNG、Drawable/资源/UI/音频结构化观察、六个 Tank 检查点、语义诊断修复与回滚、Studio/Player 同日志比较和 Game Runtime 观察卡；独立 Codex 推理与真人理解仍开放。',
  'P30 持久观察读取会验证版本、稳定身份、帧哈希和地址边界；不兼容版本要求迁移或重捕获，损坏 JSON、缺失语义 ID、错误 Checkpoint 与被篡改帧均被拒绝，成功/失败/确定性/迁移拒绝/回滚机器矩阵已闭合。',
  'P31 基础门禁已固定 Neon Bastion 美术 Skill、占位清单、16 项素材 Brief、9 个待人审视觉候选、6 类 Prefab、Prefab 运行时生成以及帮助/静音/音量控制；候选技术门禁逐项核验 PNG、尺寸、透明通道、哈希、稳定 Job/Candidate/Artifact ID 与未导入边界，真实 Electron 资源面板也已加载 9/9 预览、元数据和审核动作，默认显示“待审核 9”，并通过“全部 13”等状态筛选保留历史且证明查看不改项目；候选选择、音频、正式导入、完整包和真人验收仍开放。',
  'P31 才负责运行真实 Tank 完成 Goal；在其视觉、音频、玩法、资源与包门禁通过前，生成了素材或替换了矩形都不算完成游戏。',
  'P32 机器阶段已完成：Completion Run 串联 Goal/Plan、Tool、媒体 Job、候选、ChangeSet、Runtime、观察、测试、构建和包；命名等待点恢复、预算、三次重试上限、退避、停止保留证据、逐文件安全回滚，以及 fresh-profile 凭据/网络/脱敏/崩溃/迁移/性能/Release/已安装 Studio 聚合门禁均通过。真人 Journey D 仍由 P33 独立验收。',
  'P33 已生成具备资格的 0.4.0 角色隔离验收包：参与者只获得安装包、51 文件输入项目、哈希和任务纸，观察员获得协议、结果模板与离线校验器。校验器拒绝未执行模板，真人旅程仍待未参与开发的人完成；旧 0.3.0 开发套件仅作历史记录。',
  'P33 仍需验证安装版中的真实供应商中断恢复与整条无指导完成旅程；真人验收前严重级别空白不代表零缺陷。',
  'P22–P27 机器门禁已通过并产出 0.3.0-preview.1 Windows x64 候选包；P23-P27 真人门禁仍保持开放，当前状态是机器合格而非人类验收完成。',
  'Round 03 已证明项目文件、Schema、语义命令、ChangeSet、Codex 会话、TypeScript 沙箱、确定性 Replay、Electron Shell、Monaco、Diff 和 Windows ZIP 路径。',
  'Studio Scene/Game 已消费共享 RenderSnapshot；持久 Play/Pause/Step/Stop/Restart 保留同一 Session，DOM 游戏对象代理已从生产视口移除。',
  '产品负责人实测发现的 Scene 拖动延迟与实时输入 Tick 竞争已修复：拖动逐帧内存预览、松手单事务落盘，键鼠输入走轻量 IPC 并由 Runtime 分配权威 Tick；独立干净配置复测仍开放。',
  'Scene 交互已补齐左键拾取/空白取消、中键或右键及 Space+左键平移、滚轮缩放、Home 重置和 Q/W/E/R 工具快捷键；高频导航逐帧合并，变换松手立即回到可操作状态并在后台按 Scene 串行写入权威文件。',
  '产品负责人继续实测发现“+ 对象”等命令依赖 Electron 中不可靠的 window.prompt；全部文本输入入口已改为 Studio 内建可键盘操作对话框，“+ 对象”真实点击、命名、创建、选中和关闭对话框已通过 Electron 回归。',
  '完整门禁复查发现并修复了两项基础设施缺口：QuickJS 安全时限改为每次脚本执行重新计时，Empty/2D/3D 项目都由基础模板获得必需的 input/actions.json；旧 3D 视口源码标记断言也已改为验证真实 EngineViewport/WebGL 深度路径。',
  '2D/3D 物理均由 Collider/RigidBody 世界产生 enter/stay/exit；合成碰撞不再作为生产输入。',
  '2D 图片、静态 SVG、WAV/OGG、UI 与可达资源已贯通 Studio、脚本宿主、原生 Player 和 Windows 包；字体资源与高级 UI 仍属后续范围。',
  '3D 已使用 WebGL2/wgpu 透视与深度路径，支持层级 Transform、导入 OBJ、材质纹理、方向光、拾取导航和 3D Physics；独立真人视觉验证仍开放。',
  'File/Edit/View/Project/Run、测试发现、调用栈/Scope/Watch、受限任务输出、文件监听、专用编辑器、Git 与能力管理已通过 P26 机器门禁。',
  '中心文档现已全部显示关闭按钮，并提供关闭当前、右侧、其他和全部的选项卡右键菜单；顶部下拉菜单改为按触发按钮定位的 10px 暗色紧凑样式，真实 Electron 交互回归已覆盖三种批量关闭路径。',
  '项目打开与创建现在会在首次点击后立即进入忙碌态，锁定重复操作，并显示真实的校验、工作区索引、Codex/MCP 连接和布局恢复阶段、项目路径与等待秒数。',
  '源码编辑器已固定占用冲突容器的内容行，缺少冲突横幅时不再塌缩；文件 Inspector 操作恢复为统一暗色按钮组，并由真实 Electron 源码打开与计算样式门禁覆盖。',
  'Inspector 文件信息不再继承 Chromium 约 16px 的 definition-list 默认字号；标签固定为 9.5px、值固定为 10px，并由开发态和安装后真实 Electron 门禁测量。',
  'Monaco 已同时加载 TypeScript 语言服务与 Monarch 分词模块，TS 关键字、类型、字符串、数字、注释和括号恢复高亮；真实 Electron 门禁要求至少四组计算色，当前候选为七组。',
  '源代码管理已移除浏览器默认灰色控件：Git 工具栏、提交 Composer、变更文件状态/暂存、提交历史和 Codex ChangeSet 统一为紧凑暗色 IDE 层级；真实 Electron 与安装后门禁会拒绝浅色样式泄漏。',
  '生成与测试面板不再继承 16px 文本、18.72px 标题和灰色 outset 按钮；生成、测试、调试、能力、冲突、凭据与审批控件已统一为 9–10px 暗色层级，并由真实 Electron 逐项计算样式。',
  '右侧拖动条保留 8px 命中宽度，但可见轴已从栏内偏移位置收回中央区与右栏的真实边界；Inspector/Copilot 横向分隔不会再穿过边界，真实 Electron 会测量轴线、裁剪和内部线左缘。',
  'Studio 视觉语言已命名并锁定为 Midnight Workshop：根 AGENTS.md 强制 UI 任务读取专用 Skill，版本化 Token JSON 提供机器可读颜色/字号/几何，新增 CI 门禁会拒绝 Token 漂移、浅色表面和真实 Electron 断言退化；游戏内 UI 仍由项目美术 Skill 独立决定。',
  'Studio/Project/Agent/Goal/Context/MCP/Skill/Provider 设置已有实际消费者；未交付的语言、渲染器和构建目标明确禁用并说明原因。',
  '凭证已统一为供应商专属的命名 Profile：同一供应商可保存多个凭证，地址、地域和 Workspace 与写入后不可回读的密钥在一次表单内维护。旧全局 Provider 配置会一次性合并进命名凭证并清除，旧 schema 2 项目会补齐缺失的内置 Provider。五类生成工具分别选择供应商、凭证和模型；OpenAI/百炼远程下拉项只显示供应商 API 返回的模型及读取时间，项目静态模型不会混入。旧项目值与手动 ID 使用独立标识模式，动态图片/语音模型的就绪状态与 Broker 执行能力一致，密钥仅在 Electron 主进程解析。',
  '最新完整 npm run check 已通过，独立验证包 ZIP：abd2c43654cbafb2e93652737f1830c6172d62b25f8fcd7cffaa9794ed118d61，Tank 示例 100 次运行 57.67 秒，安装生命周期/UI 门禁通过。实际 Copilot 运行在同一 Prefab 修复的 3f2be8db… 安装版；新 Skill 已说明稳定 ID、像素裁切与局部覆写。旧真人验收包不能签署这些开发候选。',
  '独立验收交接包已经角色隔离：参与者只收到候选 ZIP、哈希与任务卡；观察员持有结构化结果模板与离线验证器，可校验四条旅程、AI 事务、输出、录屏及全部证据哈希。',
  'Round 04 人类观察尚未开始；空白严重级别不代表零缺陷，机器测试不能替代独立参与者签字。',
] as const;

export const aiParityDimensions = [
  '人类 UI',
  '项目文件',
  '读取查询',
  '语义命令',
  'MCP + Skill',
  '生成任务 + 候选审核',
  '运行帧 + 音频证据',
  '诊断 + 测试',
  'ChangeSet + 审计',
  'Undo + Rollback',
  'Goal 恢复 + 幂等',
] as const;

export const stack = [
  { kind: 'AI', value: 'Codex App Server + AGENTS / Skills' },
  { kind: 'IDE', value: 'Electron + TypeScript + React' },
  { kind: 'Protocol', value: 'Scene 2.0 + MCP + ChangeSet' },
  { kind: 'Kernel', value: 'Rust player + sandboxed project TypeScript' },
  { kind: 'Graphics', value: 'wgpu + winit' },
  { kind: 'Shader', value: 'WGSL' },
  { kind: 'Assets', value: 'Provider-neutral generation broker' },
  { kind: 'Test', value: 'Headless deterministic sim' },
] as const;

export const risks = [
  {
    title: '把“Agent 调了工具”误判为“Agent 完成了游戏”',
    level: '高',
    response:
      '最终门禁绑定实际游戏画面、声音、玩法、测试、Player 包和无指导真人结果。',
  },
  {
    title: '长 Goal 重启后重复生成或重复计费',
    level: '高',
    response:
      '先持久化稳定 Job/幂等/审批身份，恢复时先对账，未知远端状态不得直接重试。',
  },
  {
    title: 'AI 只读状态却声称视觉正确',
    level: '高',
    response:
      '提供可寻址运行帧、Drawable/UI/资源和音频证据，并要求修复前后对比。',
  },
  {
    title: '候选导入绕过人审或 ChangeSet',
    level: '高',
    response:
      '把候选决定与事务导入分离记录，所有权威文件和引用变更必须可预览、审计、回滚。',
  },
  {
    title: '美术生成吞噬范围与预算',
    level: '高',
    response:
      '先冻结风格 Skill、素材覆盖矩阵和预算；优先复用与有边界批处理，拒绝无限变体。',
  },
  {
    title: '再次把描述符当作运行能力',
    level: '高',
    response: '每项能力必须同时通过 Studio、Player、MCP、自动测试和真人任务。',
  },
  {
    title: 'Studio 与 Player 形成两个运行世界',
    level: '高',
    response: '先冻结共享 Session/Snapshot 协议，两端只做不同投影。',
  },
  {
    title: '物理与实时输入破坏确定性',
    level: '高',
    response:
      '输入归档到固定 Tick；物理步长、顺序、平台政策和 Replay 证据显式化。',
  },
  {
    title: '可见设置和按钮仍然无效',
    level: '高',
    response: '建立 settings-effect 矩阵；未接通的控件必须禁用、解释或移除。',
  },
  {
    title: '资源与供应商泄漏密钥或不可复现',
    level: '高',
    response:
      '凭据只进系统存储；项目保存 credentialRef、模型参数、哈希、成本和溯源。',
  },
  {
    title: '单人范围失控',
    level: '高',
    response: '只交付最小 2D/3D 闭环；PBR、骨骼、导航、网络和多平台明确延后。',
  },
  {
    title: 'AI 与人类再次出现能力分叉',
    level: '高',
    response: '共享命令/能力注册表，并对每项功能执行十项 AI parity 清单。',
  },
] as const;
